#!/bin/bash

bspc monitor -d 1 2 3 4 5

bspc config border_width            0
bspc config window_gap              15
bspc config normal_border_color     \#000000
bspc config focused_border_color    \#000000

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a telegram state=floating

# 환경 변수 설정
export GTK_IM_MODULE=kime
export QT_IM_MODULE=kime
export XMODIFIERS=@im=kime

# screen brightness control
brightness_level=0.7
monitor=$(xrandr | grep " connected" | cut -f1 -d" ")
xrandr --output $monitor --brightness $brightness_level

# 프로그램 실행
/usr/bin/kime-xim &
/usr/bin/feh --bg-scale --no-fehbg $HOME/.config/wallpaper/wallpaper &
$HOME/.config/polybar/launch.sh &
/usr/bin/dunst &
/usr/bin/sxhkd -c $HOME/.config/bspwm/sxhkdrc &
/usr/bin/picom -GCb &
/usr/bin/xsetroot -cursor_name left_ptr &
/usr/bin/fusuma &
/usr/bin/discord --start-minimized &

